#+TITLE: Th[is] =clamav-scan=
#+SUBTITLE: A collection of scripts for easy, faster and schedule-based clamd-scanning

* About this package
This package adds a few scripts and notifications around the clamdav service.  It is meant to reduce the amount of work to get clamd running periodically and not taking up all available resources during scans.

The configuration file defines a few paths that will be skipped during scans because they both a) contain a lot of files and b) don't have a big chance of catching infected files.

The sourcecode is largely based on [[https://gist.github.com/johnfedoruk/19820540dc096380784c8cf0b7ef333b#system-scan-notifications][this gist]] by John A. Fedoruk, with some small modifications. 


* Installation

To install this package we first need to install the dependencies, followed by the package itself.
#+begin_src sh :noweb yes 
sudo apt install clamav clamav-daemon clamav-freshclam
sudo dpkg -i clamav-scan.deb
#+end_src

To de-install =clamav-scan= and its dependencies, run the following command:
#+begin_src sh
sudo apt remove clamav-scan clamav clamav-daemon clamav-freshclam
#+end_src

* Testing
You can verify that this package works by downloading a /TEST/ virus and leaving it somewhere in your homefolder.  Its purpose is to verify a virusscanner works as expected, so its not an actual virus.  You can read more about this file, and download it from [[https://www.eicar.org/download-anti-malware-testfile/][the EICAR.org website]].

* Development
** Package version 
The package version defined here will be reflected throughout the entire package

#+name: version
#+begin_src :export none
0.5
#+end_src

** Scripts and configs
  
*** clam-scan.sh
This script will be executed to initiate the scan.  The first part of the scripts consists of scan configuration and sourcing the additional scan.conf file.
  
#+begin_src sh :mkdirp yes :tangle src/usr/local/sbin/clamav-scan :shebang "#!/bin/bash" :noweb yes
# clamav-scan.sh
export CLAMAV_SCAN_VERSION="<<get-package-version()>>"
export LOG="/var/log/clamav/scan.log"

# set defaults 
export SCAN_PATH="/home/"
export IONICE_CLASS=3
export NICE_PRIORITY=19

# source scan.conf for user customization
if [ -f "/etc/clamav/scan.conf" ]; then
  . /etc/clamav/scan.conf
fi
#+end_src

To be able to keep the currently logged in user up to date on the scanning progress, we need to be able to send them notifications.  We've added it to a function to make it reusable.  
#+begin_src sh :tangle src/usr/local/sbin/clamav-scan
# notify function, shows notifications to all logged in users
export XUSERS

function notify {
  local title=$1
  local body=$2
    
  # Send the alert to systemd logger if exist
  if [[ -n $(command -v systemd-cat) ]] ; then
    echo "$title - $body" | /usr/bin/systemd-cat -t clamav -p emerg 
  fi

  # Send an alert to all graphical users.
  XUSERS=($(who|awk '{print $1$NF}'|sort -u))
  for XUSER in $XUSERS; do
    NAME=(${XUSER/(/ })
    DISPLAY=${NAME[1]/)/}
    DBUS_ADDRESS=unix:path=/run/user/$(id -u ${NAME[0]})/bus
    echo "run $NAME - $DISPLAY - $DBUS_ADDRESS -" >> /tmp/testlog
    /usr/bin/sudo -u ${NAME[0]} DISPLAY=${DISPLAY} \
      DBUS_SESSION_BUS_ADDRESS=${DBUS_ADDRESS} \
      PATH=${PATH} \
      /usr/bin/notify-send -a "ClamAV Scan" -i security-low "$title" "$body"
  done

}
#+end_src

The following part encapsulates the actual scan.  it creates a few temporary files for output processing and then starts the scan.
This piece needs some additional love like configuring the location infected files are moved to if found
#+begin_src sh :tangle src/usr/local/sbin/clamav-scan
export SUMMARY_FILE=`mktemp`
export FIFO_DIR=`mktemp -d`
export FIFO="$FIFO_DIR/log"

export SCAN_STATUS
export INFECTED_SUMMARY

mkfifo "$FIFO"
tail -f "$FIFO" | tee -a "$LOG" "$SUMMARY_FILE" &

notify "Virus scan started" ""

echo "------------ SCAN START ------------" > "$FIFO"
echo "Running scan on `date`" > "$FIFO"
echo "Scanning $SCAN_PATH" > "$FIFO"
echo "Running with ionice class $IONICE_CLASS" > "$FIFO"
echo "Running with nice level $NICE_PRIORITY" > "$FIFO"

ionice -c $IONICE_CLASS nice -n $NICE_PRIORITY clamdscan --ping 6:5 --wait --infected --multiscan --fdpass --stdout "$SCAN_PATH" | grep -vE 'WARNING|^$' > "$FIFO"

SCAN_STATUS="${PIPESTATUS[0]}"
echo > "$FIFO" 

INFECTED_SUMMARY=`cat "$SUMMARY_FILE" | grep "Infected files"`

rm "$SUMMARY_FILE"
rm "$FIFO"
rmdir "$FIFO_DIR"
#+end_src

And finally we check the response code of the scan and notify the user about the result.  
#+begin_src sh :tangle src/usr/local/sbin/clamav-scan

if [[ "$SCAN_STATUS" -eq "1" ]] ; then
    notify "Virus signature(s) found" "$INFECTED_SUMMARY"
    exit $SCAN_STATUS
fi

if [[ "$SCAN_STATUS" -eq "2" ]] ; then
    notify "Error running virusscanner" "please check logs"
    exit $SCAN_STATUS
fi

notify "Scan complete, nothing found"
#+end_src
   
   
*** clamav.conf
#+begin_src conf :mkdirp yes :tangle src/etc/clamav/clamd.conf
# use sockets
LocalSocket /var/run/clamav/clamd.ctl
FixStaleSocket true
LocalSocketGroup clamav
LocalSocketMode 666

#
PreludeAnalyzerName ClamAV
LogFile /var/log/clamav/clamav.log
LogFileMaxSize 4294967295
LogTime yes
LogRotate yes
ExtendedDetectionInfo yes
MaxConnectionQueueLength 200
ReadTimeout 180
SendBufTimeout 500
SelfCheck 3600
User clamav
BytecodeTimeout 60000
MaxScanTime 120000
MaxRecursion 16
PCREMatchLimit 10000
PCRERecMatchLimit 5000
CrossFilesystems no
CommandReadTimeout 60
IdleTimeout 120

# this might need to be determined by the number of available CPUs
MaxThreads 4
           
# this prevents the "LibClamAV Warning: cli_realpath: Invalid arguments." error
# at least to a dir recursion of 30
MaxDirectoryRecursion 30

# exludepath regexes, do we need these? will we ever run systemwide scans?
ExcludePath ^/proc
ExcludePath ^/run
ExcludePath ^/sys
ExcludePath ^/snap

# userspace
ExcludePath \.php$
ExcludePath ^/home/.+/.steam
ExcludePath /node_modules/
ExcludePath ^/home/.+/\.config
ExcludePath /docker/volumes/
ExcludePath /\.git/
ExcludePath /docker/overlay2/
ExcludePath ^/dev
ExcludePath ^/tmp
#+end_src

*** scan.conf
#+begin_src sh :mkdirp yes :tangle src/etc/clamav/scan.conf
NICE_PRIORITY=19 # values ranging -20 to 19, with -20 getting highest priority
IONICE_CLASS=3 # only run when no other io requests -c
SCAN_PATH="/home/"
#+end_src

*** systemd.timer
#+begin_src conf :mkdirp yes :tangle src/etc/systemd/system/clamav-scan.timer
[Unit]
Description=run scan on workdays at lunchtime
Requires=clamav-daemon.service

[Timer]
OnCalendar=
OnCalendar=mon..fri 13:00
Persistent=false
Unit=clamav-scan.service

[Install]
WantedBy=timers.target
#+end_src

*** systemd.service
#+begin_src conf :mkdirp yes :tangle src/etc/systemd/system/clamav-scan.service
[Unit]
Description=nice ionized clamav scanner with notifications
Requires=clamav-daemon.service

[Service]
Type=simple
User=root
ExecStart=/usr/local/sbin/clamav-scan

[Install]
WantedBy=multi-user.target
#+end_src

** Build
This package is written using [[https://en.wikipedia.org/wiki/Literate_programming][literate progamming]] in org-mode files.  To compile the codeblock into actual scripts you'll need Emacs to "tangle" the files.  Upon tangling the scripts will automatically get the appropriate shebang and chmod changes if applicable.  Missing directories will also be created automatically.

With Emacs installed you should be able to tangle the scripts using make.
#+begin_src sh
make tangle

# the second time around you might want to run make clean first.
# make clean tangle
#+end_src

Another way is to open the =.org= file in emacs, and running =m-x org-babel-tangle ret=.

To generate the debian package you can run the =build= command.  /This command automatically runs =tangle= before generating the package so manual changes to the files will be overwritten./

#+begin_src sh
make build
## or even better:
# make clean build
#+end_src

Installing the generated scripts on your system can be done using the =install= command.  This does not use the generated Debian package, but copies the files manually instead.  To install the files, =sudo= privileges are required.
#+begin_src sh
sudo make install
#+end_src

** Docker
You can also use an Emacs Docker image to tangle the files.

 #+begin_src sh :tangle no
docker run -v ".:/app" -u `id -u`:`id -g` -e VERSION=v2.0 -w /app silex/emacs:28 emacs --batch -l org --eval "(setq org-confirm-babel-evaluate nil)" --eval "(org-babel-tangle-file \"tid-clamav.org\")"
 #+end_src

** Debian package
This package comes with Debian control and postinst files allowing us to generate a Debian package for easy installation.  The Debian package can be downloaded from the releases page. 

#+begin_src debian-control :mkdirp yes :tangle src/DEBIAN/control :noweb yes 
Package: clamav-scan
Version: <<get-package-version()>>
Maintainer: Jeroen Faijdherbe
Architecture: all
Description: Helper scripts for clamav scan automation
Depends: clamav, clamav-daemon, clamav-freshclam
#+end_src

#+begin_src sh :mkdirp yes :tangle src/DEBIAN/preinst :shebang "#!/bin/bash"
CLAMAV_CONF="/etc/clamav/clamd.conf"
BACKUP_LOCATION="/etc/clamav/clamd.conf.bck"
if [ -f "$CLAMAV_CONF" -a ! -f "$BACKUP_LOCATION" ]; then
    cp "$CLAMAV_CONF" "$BACKUP_LOCATION"
fi
#+end_src

After installation the timer will automatically activated by the installer using this =postinst= script.
#+begin_src sh :mkdirp yes :tangle src/DEBIAN/postinst :shebang "#!/bin/bash"
systemctl daemon-reload
systemctl restart clamav-daemon.service
systemctl enable --now clamav-scan.timer
#+end_src

Obligatory =prerm= script that will be invoked upon removal, disabling the timer that will be removed. 
#+begin_src sh :mkdirp yes :tangle src/DEBIAN/prerm :shebang "#!/bin/bash"
systemctl disable clamav-scan.timer
#+end_src

#+begin_src sh :mkdirp yes :tangle src/DEBIAN/postrm :shebang "#!/bin/bash"
CLAMAV_CONF="/etc/clamav/clamd.conf"
BACKUP_LOCATION="/etc/clamav/clamd.conf.bck"
if [ -f "$BACKUP_LOCATION" ]; then
    mv "$BACKUP_LOCATION" "$CLAMAV_CONF"
fi
#+end_src

** Local
Buildstep requires emacs to extract codeblocks from this document

#+begin_src sh
make clean build # requires emacs installation
sudo make install
#+end_src

enable the timer
#+begin_src sh
sudo systemctl enable --now clamav-scan.timer
#+end_src

To run the scanner immediately:
#+begin_src sh
sudo make run
# or: sudo systemctl start clamav-scan.service
#+end_src


* Version
This codeblock reads the =VERSION= environment variable and normalizes it so it can be embedded in both the Debian =control= file and the bash script.  If no =VERSION= is found, it will fall back to a default.  The output of this block can be embedded in other codeblocks using the noweb syntax.

#+NAME: get-package-version
#+BEGIN_SRC emacs-lisp :results value
(let ((version (getenv "VERSION"))
      (default "1.0.0-local"))
  (if (and version (not (string= "" version)))
      (replace-regexp-in-string "^[^0-9]*" "" version)
    default))
#+END_SRC
