name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: 28-2

    - uses: actions/checkout@v4

    - name: Build
      env:
        VERSION: ${{ github.ref_name }}
      run: 'make clean build'

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        prerelease: false
        files: build/clamav-scan.deb
